### ISSUE TITLE
Consider generating app catalog's RSS feed 

### ISSUE THREAD

**Issue by oleole39** [alexAubin/tartiflettev2#10]
Tartiflette v1 has the following PR waiting for approval which generates a RSS feed for catalog news (added/removed/broke/repaired) and adds to the dashboard's catalog page a button to subscribe to the RSS feed: https://github.com/YunoHost/tartiflette/pull/16

Since the introduction of the new app wish-list system, it would be nice to also have a RSS feed for new suggestions (or to have this included in a unique feed with labels added/removed/broke/repaired/wish?).

The RSS subscribe button would ideally be displayed on both dashboard and [app catalog](https://apps.yunohost.org/catalog) screens.

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/apps/pull/2324/commits/3ff5a3d3a70ff905038bb70e74ded4be212f3ed6 released in https://apps.yunohost.org/charts (still sort of alpha/beta so it's semi-hidden)

**Comment by alexAubin** [comment]
(I added you as co-author btw for what it's worth)

**Comment by oleole39** [comment]
Glad to see the RSS feed!
It seems it (the port?) has a few validity issues and a typo (printing some random "i" on the page): https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fapps.yunohost.org%2Fnews.rss
