### ISSUE TITLE
Menu links' behavior

### ISSUE THREAD

**Issue by oleole39** [alexAubin/tartiflettev2#11]
Can't check further now, but I just note that on the menu, all links appears when on packaging & chart pages (e.g. https://apps.yunohost.org/charts).
![image](https://github.com/alexAubin/tartiflettev2/assets/59071673/2f1642cb-d85c-43f1-a705-ff8911929539)

But only 2 of them appear when on catalog & wishlist page (e.g. https://apps.yunohost.org/catalog).
![image](https://github.com/alexAubin/tartiflettev2/assets/59071673/5c705d95-ee6f-4f60-99e8-31d53b72519c)

Is this intended not to mix "visitors" and "developpers" content ? It feels a bit strange in terms of UX for the "developpers" though.

**Comment by alexAubin** [comment]
Yes this is intended, at least since this is still in beta ...
